### ISSUE TITLE
Implement same features in Java/Android app

### ISSUE THREAD

**Issue by chetanmekha** [jishi/node-sonos-discovery#102]
Hello Jishi,
Thanks for such a nice and perfectly working api in node js for SONOS devices. 
I want to achieve same kind of functionality in android application.My query is,
1)How can i acheive this in Android app.
2) Is it possible to implement same functionality in android?
3) Have you implemented for android?
4) If I have to start then from where I can start it?

Please help me out over above queries.
Thanks,
Chetan

**Comment by jishi** [comment]
Hi. I can't help you with the Android stuff, but I can tell you that it is possible. 

For some guidance for Android, look at the Andronos source (a now deprecated controller, but I think it would still work) https://gitorious.org/andronos/andronos.git/ is a readonly copy of it.

**Comment by chetanmekha** [comment]
I am trying to run API in debug mode but it's not working. I am using Visual studio code for development.
Please guide how can I run in debug mode.

**Comment by jishi** [comment]
I'm sorry, I can assist you with specific problems that doesn't relate to this code base at all. You will have to find help by other means, stackoverflow or similar.

**Comment by chetanmekha** [comment]
Thanks for the quick reply. :)
