### ISSUE TITLE
npm test fails on spotify

### ISSUE THREAD

**Issue by laurentperez** [jishi/node-sonos-discovery#104]
Hi

Not sure what has changed, since a few days, npm test fails with 

  1) spotify should load highres art:
     Got status 401 when invoking /v1/tracks/3WKg25vrbjJlkhsgl2W4p3
  Error
      at Object.tryGetHighResArt (lib/services/spotify.js:29:10)
      at Context.it (test/unit/services/spotify.js:19:20)

Perhaps a change on spotify side ?

**Comment by laurentperez** [comment]
probably linked to https://github.com/jishi/node-sonos-http-api/pull/512

**Comment by jishi** [comment]
Yes, this is because of the new Spotify authenticated web api. I will remove that test, it doesn't really fulfill any purpose.
