### ISSUE TITLE
error: sonos.0 TypeError: Cannot read property '$text' of undefined

### ISSUE THREAD

**Issue by Guenda85** [jishi/node-sonos-discovery#113]
2019-11-08 10:43:10.339 - error: sonos.0 TypeError: Cannot read property '$text' of undefined
at EventEmitter.sax.on (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:89:28)
at emitOne (events.js:116:13)
at EventEmitter.emit (events.js:211:7)
at SAXStream.onCloseTag (/opt/iobroker/node_modules/xml-flow/lib/xml-flow.js:131:15)
at emitOne (events.js:116:13)
at SAXStream.emit (events.js:211:7)
at SAXParser.me._parser.(anonymous function) [as onclosetag] (/opt/iobroker/node_modules/sax/lib/sax.js:258:17)
at emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)
at emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)
at closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)
at SAXParser.write (/opt/iobroker/node_modules/sax/lib/sax.js:1436:13)
at SAXStream.write (/opt/iobroker/node_modules/sax/lib/sax.js:239:18)
at Readable.ondata (_stream_readable.js:639:20)
at emitOne (events.js:116:13)
at Readable.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
2019-11-08 10:43:10.340 - info: sonos.0 terminating

**Comment by jishi** [comment]
Which version are you running? Check the package.json file.

**Comment by Guenda85** [comment]
1.1.3

/opt/iobroker/node_modules/sonos-discovery$ cat package.json
{
  "_args": [
    [
      {
        "raw": "sonos-discovery@https://github.com/jishi/node-sonos-discovery/archive/v1.1.3.tar.gz",
        "scope": null,
        "escapedName": "sonos-discovery",
        "name": "sonos-discovery",
        "rawSpec": "https://github.com/jishi/node-sonos-discovery/archive/v1.1.3.tar.gz",
        "spec": "https://github.com/jishi/node-sonos-discovery/archive/v1.1.3.tar.gz",
        "type": "remote"
      },
      "/opt/iobroker/node_modules/iobroker.sonos"
    ]
  ],
  "_from": "https://github.com/jishi/node-sonos-discovery/archive/v1.1.3.tar.gz",
  "_id": "sonos-discovery@1.1.3",
  "_inCache": true,
  "_location": "/sonos-discovery",
  "_phantomChildren": {},
  "_requested": {
    "raw": "sonos-discovery@https://github.com/jishi/node-sonos-discovery/archive/v1.1.3.tar.gz",
    "scope": null,
    "escapedName": "sonos-discovery",
    "name": "sonos-discovery",
    "rawSpec": "https://github.com/jishi/node-sonos-discovery/archive/v1.1.3.tar.gz",
    "spec": "https://github.com/jishi/node-sonos-discovery/archive/v1.1.3.tar.gz",
    "type": "remote"
  },
  "_requiredBy": [
    "/iobroker.sonos",
    "/sonos-web-controller"
  ],
  "_resolved": "https://github.com/jishi/node-sonos-discovery/archive/v1.1.3.tar.gz",
  "_shasum": "c1a332a639271315858714bb122b517f89723db2",
  "_shrinkwrap": null,
  "_spec": "sonos-discovery@https://github.com/jishi/node-sonos-discovery/archive/v1.1.3.tar.gz",
  "_where": "/opt/iobroker/node_modules/iobroker.sonos",
  "author": {
    "name": "Jimmy Shimizu",
    "email": "jimmy@shimizu.se"
  },
  "bugs": {
    "url": "https://github.com/jishi/node-sonos-discovery/issues"
  },
  "dependencies": {
    "html-entities": "1.0.x",
    "request-promise": "^1.0.2",
    "xml-flow": "^1.0.1"
  },
  "description": "A simple node library for managing your Sonos system",
  "devDependencies": {
    "chai": "*",
    "jscs": "^3.0.7",
    "jshint": "~2.8.0",
    "mocha": "*",
    "proxyquire": "^1.7.3",
    "rewire": "^2.5.1",
    "sinon": "^1.17.2",
    "sinon-as-promised": "^4.0.0",
    "sinon-chai": "^2.8.0"
  },
  "engine": "node 4.x.x",
  "homepage": "https://github.com/jishi/node-sonos-discovery#readme",
  "main": "lib/SonosSystem.js",
  "name": "sonos-discovery",
  "optionalDependencies": {},
  "readme": "[![Build Status](https://travis-ci.org/jishi/node-sonos-discovery.svg?branch=refactor-with-promises)](https://travis-ci.org/jishi/node-sonos-discovery)\n\nnode-sonos-discovery\n--------------------\n\nThis is a simplification of the Sonos implementation of UPnP for the node.js stack. This library will allow you to interact with your sonos system with simple commands like play, pause, next etc, but is expected to be ran at all times because it keeps track of the players.\n\n1.0.0 is totally rewritten to be promised based!\n\nFor example integrations, please see the following projects:\n\nhttps://github.com/jishi/node-sonos-http-api\n\nhttps://github.com/jishi/node-sonos-web-controller (old version)\n\n\nOptions\n-------\n\n\n\nContributions\n-------------\n\nIf you are sending a pull request, please run:\n\n`npm test`\n\nBefore submitting it, to validate syntax with jscs and run the few tests in there. Thank you!\n",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jishi/node-sonos-discovery.git"
  },
  "scripts": {
    "jscs": "jscs lib test",
    "mocha": "mocha test/unit --recursive",
    "test": "npm run -s jscs && npm run -s mocha"
  },
  "version": "1.1.3"
}

**Comment by jishi** [comment]
That's a really old version, and I believe it has been fixed since.

What software are you running? Sonos-discovery is just a library.

**Comment by Guenda85** [comment]
I’m jusing ioBroker with sonos adapter 1.7.7 (https://github.com/ioBroker/ioBroker.sonos)


Von: Jimmy Shimizu <notifications@github.com>
Gesendet: Freitag, 8. November 2019 13:27
An: jishi/node-sonos-discovery <node-sonos-discovery@noreply.github.com>
Cc: Günter Keilhammer <Guenter@keilhammer.com>; Author <author@noreply.github.com>
Betreff: Re: [jishi/node-sonos-discovery] error: sonos.0 TypeError: Cannot read property '$text' of undefined (#113)

That's a really old version, and I believe it has been fixed since.

What software are you running? Sonos-discovery is just a library.

**Comment by jishi** [comment]
Original software needs to use a newer version, closing. 

https://github.com/ioBroker/ioBroker.sonos/issues/57
