### ISSUE TITLE
using bonding interface

### ISSUE THREAD

**Issue by neophob** [jishi/node-sonos-discovery#38]
Hi

I'm using the network bonding module, now sonos-discovery does not discover any sonos device anymore. and hints how to make this works?

**Comment by jishi** [comment]
Could you be a bit more specific? Are you talking about network bonding in linux? Could you paste an ifconfig output?

**Comment by neophob** [comment]
yes exactly, I use the linux bonding module in linux:

```
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 192.168.111.23  netmask 255.255.255.0  broadcast 192.168.111.255
        inet6 fe80::3cb8:5fff:fea0:e563  prefixlen 64  scopeid 0x20<link>
        ether 02:0f:0a:81:c4:98  txqueuelen 0  (Ethernet)
        RX packets 145929  bytes 203369863 (193.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26877  bytes 2640778 (2.5 MiB)
        TX errors 0  dropped 3 overruns 0  carrier 0  collisions 0

eth0: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        inet6 fe80::f:aff:fe81:c498  prefixlen 64  scopeid 0x20<link>
        ether 02:0f:0a:81:c4:98  txqueuelen 1000  (Ethernet)
        RX packets 145927  bytes 203369863 (193.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26877  bytes 2640778 (2.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 47

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 237  bytes 19543 (19.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 237  bytes 19543 (19.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=6147<UP,BROADCAST,SLAVE,MULTICAST>  mtu 1500
        ether 5c:f3:70:20:55:21  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

as soon as I assign eth0 an ip adress, discovery works.

**Comment by jishi** [comment]
Well, it could be that node.js doesn't find the bonding interface, which doesn't allow me to bind the multicast to any relevant IP. If I don't find any, it will revert to binding to 0.0.0.0 which, I believe should work, but maybe this fails since it actually has interfaces (without IP). 

I initially made this to make it work in multiple NIC-scenarios, but it probably disturbs your setup. It should info-log "relevant IPs" during startup, do you see that output? (row 130 in sonos.js), otherwise, if you could output the info it tries to discover during that phase, it might tell whats going on.

**Comment by neophob** [comment]
I think your post and my update were made at the same time - I added the detected network interfaces above. bond0 looks like a regular address

**Comment by jishi** [comment]
Either the bond0 interface doesn't handle multicast correctly for some reason, or the tun0 interface (which uses the same IP) disrupt things. Could you try and comment out the for loop at row 119 in sonos.js? That would revert it to just bind on all interfaces and send the udp data on the first available interface. That would give a clue if the fault is because of the address binding or if it is the bond0 interface that gives you trouble.

**Comment by neophob** [comment]
I disabled tun0 interface to out this out - and it still didn't work. So it might be the some issue with the bond0 interface (routing issue?). But I'll try to use 0.0.0.0 for listening, if this helps I'll create a patch. maybe it would make sense to blacklist/whitelist interfaces, for example all those localhosts interfaces.

**Comment by jishi** [comment]
I already skip any interface that is marked as internal, so they are not a problem. And the number of interfaces shouldn't matter. How are you bonding the interfaces? If you add an IP to wlan0, does it still work? Maybe the bond is sending traffic the wrong way?

**Comment by neophob** [comment]
Using 0.0.0.0 does the trick. I think the problem is that bond0 and tun0 use the same ip:

{code}
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 192.168.0.52  netmask 255.255.255.0  broadcast 192.168.0.255

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 192.168.0.52  netmask 255.255.255.255  destination 192.168.0.52
{code}

I assume as we specify only the ip address the wrong interface (in my case tun0) is used, thus no players are found. I propose that we add an option to listen on 0.0.0.0 instead on a specific interface. What do you think?

**Comment by jishi** [comment]
Well, you said that you disabled tun0 for testing, and it still didn't work? I would really like to understand what is going on here, could you share your bonding configuration and some simple steps on how to replicate this setup?

**Comment by neophob** [comment]
Yes I said that, but it make sense now. I took down the tun0 interface and then I tested it but I must have forgotten to restart my application. Because after I update this issue-text suddenly my Sonos was discovered and I was puzzled why it was working.

Anyway to reproduce you need an interface without access to the network where Sonos is (like the tun0 interface) AND the the name of this dummy interface must be lexically AFTER your real interface (bond0 vs. tun0) AND they need to have the same IP. They you should reproduce this issue.

However I don't really know where the problem is, maybe node or os related. We create a socket and bind this socket to an IP. The OS has two NIC's with the same IP's - so it might be undefined which interface is choosen?

**Comment by jishi** [comment]
When you bind the socket, you just specify an IP-address. Which interface it actually choose to bind to, will be up to the OS and in your case it probably bound it to tun0. 

But why do you have a tunnel-interface with the same IP as the bond interface? That seems like it might give you more headaches further down the road..

**Comment by neophob** [comment]
Yes thats correct, the tun has the same IP as the bond0 interface.
