### ISSUE TITLE
Missing infos?

### ISSUE THREAD

**Issue by ColdFireIce** [jishi/node-sonos-discovery#70]
Hi,

while working with the code i notices, that some features seem to be missing.

- currentTrack.type like radio/input/track
- radio infos like: streamcontent and radioshowmd
- using EnqueuedTransportURIMetaData to replace the title while radio is on
- repeat has 2 states repeatAll and repeatOne, but is only represented as bool

Who should these features be handled? This time I'm asking before creating pull request ;)

Greetings

**Comment by jishi** [comment]
Yes, I'm aware of these, have been low prio. 

type has no built-in support from sonos, needs to be identified based on the current uri. There are a couple of these checks so it should be consolidated, preferably.

Radio-data should replace artist/title when updating state, or use another format based on type. But probably easier to re-use fields, for people integrating.

I haven't come up with a good solution for repeat yet. I guess a tri-state enum would be appropriate, "no, one, all" or something.

**Comment by ColdFireIce** [comment]
Do you have some information on when to best use what value vor what?
r:resmd
r:streamcontent
r:radioshowmd

My  'r:radioshowmd' contains some weird strings like : "Die Kai-Karsten-Show,p272958" the ",p272958" part is not shown in die sonos app. is there a structure for this, to know about?

Is there a better way to check if a player is on input mode the starting with "x-rincon-stream:"?

should that "input mode" be part of the Player.state or the Player.state.currenttrack?

**Comment by jishi** [comment]
This is what I did in the old version:

https://github.com/jishi/node-sonos-discovery/blob/legacy/lib/player.js#L258-L264

The type should probably go into the track (since another track might not be a radio, in theory at least). just extract the helper function as a requirable function, would be my suggestion.

**Comment by ColdFireIce** [comment]
Yeah I'll use that to replace the title.
So no idea on the strange 'r:radioshowmd' ?

I'm not quite sure what you mean with "extract the helper function as a requirable function". My nodejs skills aren't at master-level, yet ;)

**Comment by ColdFireIce** [comment]
Hi,

could you explain me what the "outputFixed" param does?

Thanks, and Greetings

**Comment by jishi** [comment]
It's a flag indicating that a device (only the connect) is configured for
fixed output volume (bitstream) i.e max output when you control it only via
your receiver/amplifier.

**Comment by ColdFireIce** [comment]
A ok thanks :)

**Comment by jishi** [comment]
Closing since we have active pull requests for them
