### ISSUE TITLE
Support Google Play Music (I'm feeling Lucky mix)

### ISSUE THREAD

**Issue by neophob** [jishi/node-sonos-discovery#76]
When the Google Play Music "I'm feeling Lucky mix" is selected in Sonos, this (streaming) mode is not detected by Sonos discovery. This URI looks like:

```
"uri": "x-sonosprog-http:_dklxfo-EJNFGf4fhhl5zLwSxbZ-NIJgqG7UK83SzxsF8y9ZJwK58ehTTw3hKlMO.mp3?sid=151&flags=8192&sn=8",
```

I guess "x-sonosprog-http" needs to be added to the getUriType.js / isRadio check, right?

**Comment by jishi** [comment]
Hi, this is already checked in the http api (atleast in beta https://github.com/jishi/node-sonos-http-api/blob/beta/lib/helpers/is-radio-or-line-in.js) as well as in the master branch of discovery https://github.com/jishi/node-sonos-discovery/blob/master/lib/prototypes/Player/getUriType.js

The track type is however not released yet, it was added this week. But you guys are still using the old version of http-api, correct?

**Comment by neophob** [comment]
Oh great, I missed that. Yes we currently use the legacy version - I updated this code in my branch. thanks
